-- 코드를 입력하세요
SELECT USER_ID, NICKNAME, Sum(PRICE) AS TOTAL_SALES
FROM USED_GOODS_USER AS user
JOIN USED_GOODS_BOARD AS board
    ON board.WRITER_ID = user.USER_ID
WHERE STATUS = "DONE"
GROUP BY USER_ID
HAVING TOTAL_SALES >= 700000
ORDER BY TOTAL_SALES;