-- 코드를 입력하세요
SELECT p.CATEGORY, p.PRICE AS MAX_PRICE, p.PRODUCT_NAME
FROM (SELECT CATEGORY, (MAX(PRICE)) AS MAX_PRICE, PRODUCT_NAME
        FROM FOOD_PRODUCT 
        WHERE CATEGORY IN ('과자', '국', '김치', '식용유')  
        GROUP BY CATEGORY) AS sub
JOIN FOOD_PRODUCT AS p
ON p.CATEGORY = sub.CATEGORY AND p.PRICE = sub.MAX_PRICE
ORDER BY PRICE DESC;

